### ISSUE TITLE
Order of rewards for early users

### ISSUE THREAD

**Issue by MonsterWong** [baizhiheizi/prsdigg#30]
E.g. After user A purchased the article X,  user B also completed the purchase payment. 
After that, the user A rewarded the article, and the user B was regarded as one of the early users before the behavior of reward, so he participated in the reward sharing.

Is this understanding correct?

**Comment by an-lee** [comment]
> E.g. After user A purchased the article X, user B also completed the purchase payment.
> After that, the user A rewarded the article, and the user B was regarded as one of the early users before the behavior of reward, so he participated in the reward sharing.
> 
> Is this understanding correct?

Correct.
