### ISSUE TITLE
文商 reader reward → Reflection to the author

### ISSUE THREAD

**Issue by yancyan5588** [baizhiheizi/prsdigg#491]
文商
The other day's reader reward → The time lag of reflecting the author's reward, is the processing slow enough to wait for a few days to a few weeks?

Does the processing speed change depending on the amount of BTC?  It seems that it will take a long time if it is 0.001 BTC or more.

**Comment by yancyan5588** [comment]
文商 reader reward → Reflection to the author

The other day's reader reward → The time lag of reflecting the author's reward, is the processing slow enough to wait for a few days to a few weeks?

Does the processing speed change depending on the amount of BTC?  It seems that it will take a long time if it is 0.001 BTC or more.

**Comment by yancyan5588** [comment]
Because the reader rewards from 3 days ago haven't been reflected to me as the author yet.

**Comment by an-lee** [comment]
> Because the reader rewards from 3 days ago haven't been reflected to me as the author yet.

@yancyan5588 would you provide the article's uuid(or title), the reward's payer and the paid time? I'll check it out.

**Comment by yancyan5588** [comment]
This 文商 3article.  Are you sure you want this URL?

https://bunshow.jp/articles/98cb0738-1329-4989-bc64-ed7109527817

https://bunshow.jp/articles/5484371f-6b13-45c6-a25b-8f996afa962f

https://bunshow.jp/articles/117672cd-cda9-4930-984a-22d5d058d1ea

**Comment by yancyan5588** [comment]
The payer of the reward is Mr. Anakin.  I have received dozens of articles according to the three articles.  Do I need to provide all reward time?

**Comment by yancyan5588** [comment]
The payer of the reward is レインメーカー(アナキン)

**Comment by an-lee** [comment]
> This 文商 3article. Are you sure you want this URL?
> 
> https://bunshow.jp/articles/98cb0738-1329-4989-bc64-ed7109527817
> 
> https://bunshow.jp/articles/5484371f-6b13-45c6-a25b-8f996afa962f
> 
> https://bunshow.jp/articles/117672cd-cda9-4930-984a-22d5d058d1ea

All payments from レインメーカー(アナキン) hasn't been distributed to authors and readers. I've distributed them manually. There's must a bug here I'm still looking for. 

Sorry for the troubles. And thanks for reporting it! @yancyan5588

**Comment by yancyan5588** [comment]
Good morning.  The accumulated reader rewards have entered the author.  Was it a bug?  I hope it will be resolved in the future.  Thank you

**Comment by an-lee** [comment]
should be fixed in https://github.com/baizhiheizi/prsdigg/commit/8fe017cc2b2b7a071b13815ab94a4266164c3ae3
